before_script:
- ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
- brew install node
- brew install npm


build:
    script:
    - cd backend && npm install
    - cd ../WebApp && npm install
    - npm run dev