image: node:8.11.1

stages:
  - deploy

before_script:
  - cd backend && yarn install
  - cd ../WebApp && yarn install
  - npm install -g now

deploy:
  stage: deploy
  script:
    - cat $NOW_TOKEN
    - npm run deploy
    - npm run alias
    - npm run now-rm
