before_script:
- env
- sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
- brew install node
- brew install npm


build:
    script:
    - cd backend && npm install
    - cd ../WebApp && npm install
    - npm run dev