image: node:8.11.1

stages:
  - build
  - test
  - deploy

before_script:
  - cd backend && yarn install
  - cd ../WebApp && yarn install
  - npm install -g now

build_WebApp:
  stage: build
  script:
    - yarn build

test_WebApp:
  stage: test
  script:
    - curl -O https://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip
    - sudo apt-get install zip unzip
    - unzip chromedriver_linux64.zip
    - rm chromedriver_linux64.zip
    - yarn test

deploy_to_neomkt-test.now.sh:
  stage: deploy
  script:
    - npm run deploy
    - npm run alias
    - npm run now-rm
