image: node:8.11.1

stages:
  - build
  - test
  - deploy

before_script:
  - cd backend && yarn install
  - cd ../WebApp && yarn install
  - npm install -g now

build:
  stage: build
  script:
    - cd WebApp
    - yarn build

test:
  stage: test
  script:
    - cd WebApp
    - yarn test

deploy:
  stage: deploy
  script:
    - now
